name: unet2d-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<2.0         
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - tqdm
  - nibabel
  - pytorch           
  - torchvision
  - torchaudio
  - pip