name: unet2d-env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - nibabel
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - torch==2.9.1
      - torchvision==0.24.1
      - torchaudio==2.9.1
      - --index-url https://download.pytorch.org/whl/cu126